import { FluidSubcategory } from './types';

export const FLUID_SPECS: Record<FluidSubcategory, { required: string; examples: string[]; slang: string[]; armenian: string[] }> = {
  engine_oil: {
    required: 'viscosity',
    examples: ['0W-20', '5W-30', '10W-40', '5W-20'],
    slang: ['1040', '0520', '0530', '1030'],
    armenian: ['մատոռի յուղ', 'սինթետիկ', 'հանքային'],
  },
  transmission_fluid: {
    required: 'spec',
    examples: ['Toyota WS', 'ATF+4', 'Dexron VI', 'CVT Fluid', 'Mercon V'],
    slang: ['ATF', 'CVT', 'transmission oil'],
    armenian: ['կարոբկի յուղ', 'կարոբկի ձեթ'],
  },
  differential_fluid: {
    required: 'viscosity',
    examples: ['75W-90', '80W-90', '75W-140'],
    slang: ['gear oil', 'diff oil'],
    armenian: ['դիֆերենցիալի յուղ', 'մոստի յուղ'],
  },
  gear_oil: {
    required: 'viscosity',
    examples: ['75W-90', '80W-90'],
    slang: ['gear oil'],
    armenian: ['գիր օյլ'],
  },
  transfer_case_fluid: {
    required: 'spec',
    examples: ['Auto-Trak II', 'ATF', 'Gear Oil'],
    slang: ['transfer case oil'],
    armenian: ['ռազդատկի յուղ'],
  },
  brake_fluid: {
    required: 'DOT type',
    examples: ['DOT 3', 'DOT 4', 'DOT 5.1'],
    slang: ['brake oil'],
    armenian: ['տորմուզի յուղ', 'տորմուզի ձեթ'],
  },
  coolant: {
    required: 'family/color',
    examples: ['Asian Blue', 'HOAT', 'OAT', 'Super Long Life'],
    slang: ['antifreeze', 'radiator fluid'],
    armenian: ['անտիֆրիզ', 'ռադիատորի ջուր'],
  },
  power_steering_fluid: {
    required: 'spec',
    examples: ['Dexron III', 'PSF'],
    slang: ['steering oil'],
    armenian: ['ղեկի յուղ'],
  },
};

export const COROLLA_2022_SPECS = {
  engine_oil: '0W-20',
  transmission: 'Toyota Genuine CVTF FE',
  brake_fluid: 'DOT 3',
  coolant: 'Toyota Super Long Life Coolant',
  steering: 'Electric (No Fluid)',
};

export const TRIMS_2022_COROLLA = ['L', 'LE', 'SE', 'XLE', 'XSE', 'Nightshade', 'Apex Edition'];

export const US_STATES = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
];
